[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   server role = standalone server

   security = user
   map to guest = never
   restrict anonymous = 2
   usershare allow guests = no

   disable netbios = yes

   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

   access based share enum = yes

   log file = /var/log/samba/libraryit-samba.log
   max log size = 0
   log level = 2


[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   guest ok = no

   valid users = @readonly @staff
   read only = yes
   write list = @staff

   force group = staff
   create mask = 0664
   directory mask = 0775

   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = all
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE


[papers]
   path = /libraryit/papers
   browseable = yes
   guest ok = no

   valid users = @readonly @staff
   read only = yes
   write list = @staff

   force group = staff
   create mask = 0664
   directory mask = 0775

   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = all
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE


[SourceCode]
   path = /libraryit/sourcecode
   browseable = yes
   guest ok = no

   valid users = @staff
   read only = yes

   force group = staff
   create mask = 0640
   directory mask = 0750

   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = all
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE


[docs]
   path = /libraryit/docs
   browseable = yes
   guest ok = no

   valid users = @readonly @staff
   read only = yes
   write list = librarian

   force group = staff
   create mask = 0644
   directory mask = 0755

   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = connect disconnect openat pwrite pread renameat unlinkat
   full_audit:failure = connect openat pwrite pread renameat unlinkat
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE